name: bilibili_clone
description: A Bilibili clone app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 核心依赖（确保无冲突）
  provider: ^6.0.5
  cached_network_image: ^3.3.0
  image_picker: ^1.2.0
  video_player: ^2.8.0
  chewie: ^1.7.0
  font_awesome_flutter: ^10.7.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  universal_html: ^2.2.4
  
  # 可选依赖（可暂时移除）
  # file_picker: ^5.5.0  # 更旧的稳定版本
  # share_plus: ^7.2.1   # 更旧的稳定版本
  
  # Firebase 相关
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  # google_sign_in: ^7.2.0  # 暫時禁用
  
  # 权限管理
  permission_handler: ^12.0.1
  file_picker: ^10.3.3
  
  # 圖表庫
  fl_chart: ^0.69.0
  
  # 網絡連接檢測
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/